name: linext Compiler v2.9-SID

on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: 'Run on'
        default: 'ubuntu-latest'
        required: true
        type: string

      name:
        description: 'Name'
        default: '4.14-kernel'
        required: true
        type: string
      
      kernel-url:
        description: 'Kernel-url'
        default: 'https://github.com/malkist01/Ginkgo.git'
        required: true
        type: string

      kernel-branch:
        description: 'Kernel-branch'
        default: 'susfs'
        required: true
        type: string

      kernel-config:
        description: 'Kernel-config'
        default: 'vendor/ginkgo_defconfig'
        required: true
        type: string

      AK3:
        description: 'AnyKernel3'
        default: 'https://github.com/malkist01/AnyKernel3'
        required: true
        type: string

jobs:
  linext-24:
    runs-on: ${{ inputs.ubuntu }}
    container: 
      image: debian:sid
      options: --user root

    steps:
    # =========================
    # Setup Packages (FIXED)
    # =========================
    - name: Setup Packages
      run: |
            apt-get update
            apt-get install -y \
            clang lld llvm \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            binutils-aarch64-linux-gnu \
            binutils-arm-linux-gnueabi \
            make bc bison flex libssl-dev python3 \
            git zip build-essential

    # =========================
    # Kernel Clone (FIXED BRANCH)
    # =========================
    - name: Setup Kernel
      run: |
        git clone --depth=1 -b ${{ inputs.kernel-branch }} ${{ inputs.kernel-url }} kernel-dir

    # =========================
    # Build Kernel
    # =========================
    - name: Compile
      run: |
        mkdir -p out
        cd kernel-dir

        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER="linex"
        export KBUILD_BUILD_HOST="Project"

        make -j$(nproc --all) ${{ inputs.kernel-config }} O=out all \
              CC="ccache clang" \
              LD=ld.lld \
              LLVM=1 \
              LLVM_IAS=1 \
              CROSS_COMPILE=aarch64-linux-gnu- 2>&1 | tee $OUT_DIR/build.log


    # =========================
    # AnyKernel3
    # =========================
    - name: AnyKernel3
      run: |
        git clone -b ginkgo ${{ inputs.AK3 }} AnyKernel3

        cp out/arch/arm64/boot/Image* AnyKernel3/ 2>/dev/null || true
        cp out/arch/arm64/boot/dtb* AnyKernel3/ 2>/dev/null || true

        cd AnyKernel3
        zip -r9 ../kernel.zip *

    # =========================
    # Upload
    # =========================
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}"
        path: kernel.zip
