# Annoy Project
name: 4.14-susfs
on:
  workflow_dispatch:
    inputs:
      ubuntu:
        description: 'Run on'
        default: 'ubuntu-22.04'
        required: true
        type: string
      name:
        description: 'Name'
        default: 'Ginkgo-susfs'
        required: true
        type: string
      compiler:
        description: 'Compiler | gcc|clang|llvm'
        default: 'gcc'
        required: true
        type: string
      aosp-clang:
        description: 'Clang | false for disable'
        default: 'false'
        required: true
        type: string
      kernel-url:
        description: 'Kernel-url'
        default: 'https://github.com/malkist01/Ginkgo.git'
        required: true
        type: string
      kernel-branch:
        description: 'Kernel-branch'
        default: 'susfs'
        required: true
        type: string
      kernel-config:
        description: 'Kernel-config'
        default: 'vendor/ginkgo_defconfig'
        required: true
        type: string
      disable-lto:
        description: 'Disable LTO'
        default: 'true'
        required: true
        type: string
      AK3:
        description: 'AnyKernel3'
        default: 'https://github.com/malkist01/AnyKernel3.git'
        required: true
        type: string
jobs:
  linext-24:
    runs-on: ${{ inputs.ubuntu }}
    steps:
    - name: Checkin
      run: |
         echo "name: ${{ inputs.name }}"
         echo "compiler: ${{ inputs.compiler }}"
         echo "aosp-clang: ${{ inputs.aosp-clang }}"
         if [ ${{ inputs.kernel-url }} != false ]; then
            echo "kernel-url: ${{ inputs.kernel-url }}"
            echo "kernel-branch: ${{ inputs.kernel-branch }}"
         fi
         if [ ${{ inputs.kernel-url }} == false ]; then
            echo "kernel-url: use current repo"
            sudo timedatectl set-timezone Asia/Jakarta
            if [ ${{ inputs.kernel-branch }} != main ]; then
               echo "custom-sc: ${{ inputs.kernel-branch }}"
            fi
            if [ ${{ inputs.kernel-branch }} == main ]; then
               echo "custom-sc: disable"
            fi
         fi
         echo "kernel-config: ${{ inputs.kernel-config }}"
         echo "kernelsu: ${{ inputs.kernelsu }}"
         echo "disable-lto: ${{ inputs.disable-lto }}"
         echo "Annoy Project"
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Packages
      run: |
         sudo timedatectl set-timezone Asia/Jakarta
         sudo apt update -y
         sudo apt-get update -qq
         sudo apt-get install -y --no-install-recommends python3-pip git zip unzip gcc g++ make ninja-build file bc bison flex libfl-dev libssl-dev libelf-dev wget build-essential python3-dev python3-setuptools rsync ccache llvm-dev libncurses6 libfdt-dev binwalk
         aria2c -q https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh && NONINTERACTIVE=1 bash ./uninstall.sh -f -q
         if [ -f /bin/swapon ]; then
             export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
             sudo swapoff $SWAP_FILE
             sudo rm $SWAP_FILE
             sudo fallocate -l 16G $SWAP_FILE
             sudo chmod 600 $SWAP_FILE
             sudo mkswap $SWAP_FILE
             sudo swapon $SWAP_FILE
             unset SWAP_FILE
         fi
    - name: Setup GCC
      run: |
            mkdir -p -v $HOME/gcc-64
            git clone --depth=1 https://github.com/StatiXOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-elf $HOME/gcc-64
            mkdir -p -v $HOME/gcc-32
            git clone --depth=1 https://github.com/StatiXOS/android_prebuilts_gcc_linux-x86_arm_arm-eabi $HOME/gcc-32
    - name: Setup Kernel
      run: |
         if [ ${{ inputs.kernel-url }} != false ]; then
            git clone --depth=1 ${{ inputs.kernel-url }} -b ${{ inputs.kernel-branch }} kernel-dir
         else
            if [ ${{ inputs.kernel-branch }} != main ]; then
               ${{ inputs.kernel-branch }}
            else
               echo "custom-sc: disable"
            fi
            ls
         fi
    - name: LTO
      run: |
         if [ ${{ inputs.kernel-url }} != false ]; then
            cd kernel-dir
         fi
         if [ ${{ inputs.disable-lto }} = true ]; then
             if grep -q "LTO" "arch/arm64/configs/${{ inputs.kernel-config }}"
             then
                  sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/arm64/configs/${{ inputs.kernel-config }} 
                  sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/arm64/configs/${{ inputs.kernel-config }} 
                  sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/arm64/configs/${{ inputs.kernel-config }} 
                  echo "CONFIG_LTO_NONE=y" | tee -a arch/arm64/configs/${{ inputs.kernel-config }} >/dev/null
             fi
         fi
    - name: Compile
      run: |        
         mkdir -p -v out
         cd kernel-dir
          export PATH=$HOME/gcc-64/bin:$HOME/gcc-32/bin:$PATH
          make O=out ARCH=arm64 vendor/ginkgo_defconfig
          make -j$(nproc --all) O=out CROSS_COMPILE_ARM32=arm-eabi- CROSS_COMPILE=aarch64-elf- AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump CC=aarch64-elf-gcc STRIP=llvm-strip CONFIG_DEBUG_SECTION_MISMATCH=y
    - name: AnyKernel3
      run: |
          git clone -b ginkgo ${{ inputs.AK3 }} AnyKernel3
          rm -rf AnyKernel3/.git AnyKernel3/.github AnyKernel3/LICENSE AnyKernel3/README.md AnyKernel3/modules AnyKernel3/patch AnyKernel3/ramdisk
          if [[ -f out/arch/arm64/boot/Image.gz-dtb ]]; then
            cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/Image.gz-dtb
          elif [[ -f out/arch/arm64/boot/Image-dtb ]]; then
            cp out/arch/arm64/boot/Image-dtb AnyKernel3/Image-dtb
          elif [[ -f out/arch/arm64/boot/Image.gz ]]; then
            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
          elif [[ -f out/arch/arm64/boot/Image ]]; then
            cp out/arch/arm64/boot/Image AnyKernel3/Image
          fi
          if [ -f out/arch/arm64/boot/dtbo.img ]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
          fi
    - name: Upload
      run: |
          mkdir Upload
          cp -rf AnyKernel3/* Upload
    - id: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.name }}"
        path: Upload/*
        
# Enjoy Your Life....
